[workspace]
resolver = "3"

members = [
  "crates/monet",
  "examples/*",
  "crates/monoio",
  "crates/monoio-compat",
  "crates/monoio-macros",
]

[workspace.lints.clippy]
macro_use_imports = "warn"

